Disable pytest execution of flake8 for this package only.
As of https://github.com/pytest-dev/pytest/pull/3751/, pytest will insist on
importing all files it runs flake8 on. This fails in sconsUtils with an:

  ImportError: lsst.sconsUtils cannot be imported outside an scons script

sconsUtils should still be checked for flake8 compliance by Travis.